#!/usr/bin/env python

import sys
import optparse
import os
from subprocess import PIPE, Popen, STDOUT


class OptionParser(optparse.OptionParser):
    """Customised OptionParser class with 
    extra feature 'check_required'"""
    def check_required(self, opt):
        """Throws error if opt is not included"""
        option = self.get_option(opt)

        if getattr(self.values, option.dest) is None:
            self.error("%s option not supplied" % option)

def main(parses):
    """Main function"""
    options, args = parses

    p = Popen('ls data/*.fits', stdout=PIPE, shell=True, stderr=PIPE)
                
    result, error = p.communicate()

    if len(error) != 0:
        print error,
        sys.exit(1)

    files = []

    for file in result.split():
        files.append(file)

    print len(files) 

if __name__ == "__main__":

    parser = OptionParser()
    
    #parser.add_option('-v', '--verbose', action='store_true',
    #        dest='verbose', default=False, 
    #        help='Print extra logging information')

    options, args = parser.parse_args()



    main((options, args))




#if __name__ == "__main__":
#    #set up command line options
#    parser = OptionParser(usage = "usage: %prog [options] "\
#            + "-l time_low -h time_high <dir>",
#            version = "%prog 0.1",
#            conflict_handler="resolve")
#
#    parser.add_option('-l', '--low', action="store", type="string", 
#            dest="time_low", help="Lower time limit",
#            metavar="time_low")
#
#    parser.add_option('-h', '--high', action="store", type="string", 
#            dest="time_high", help="Higher time limit",
#            metavar="time_high")
#
#    parser.add_option('-d', '--dir', action='store', type='string',
#            dest='dir', help='Directory to store files', default='',
#            metavar='dir')
#
#    parser.add_option('-n', '--no-cpy', action='store_true', dest='no_cpy',
#            default=False, help='Dry run: do not actually copy files')
#
#    parser.add_option('-v', '--verbose', action='store_true',
#            dest='verbose', default=False, 
#            help='Print extra logging information')
#
#
#    options, args = parser.parse_args()
#
#    #compulsary arguments
#    parser.check_required("-l")
#    parser.check_required("-h")
#
#    if len(args) != 1:
#        #print >> sys.stderr, "Source directory argument required"
#        print("Source directory argument required", file=sys.stderr)
#        exit(1)
#
#
#    main((options, args))
